version: '3'
services:
  back:
    container_name: svelte-template-backend
    build: backend/
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_migrations/:/pb_migrations
      - ./backend/pb_data/:/pb_data/
  front:
    container_name: svelte-template-frontend
    build: frontend/
    volumes:
      - ./frontend/src/:/app/src
    ports:
      - "5173:5173"
    env_file:
      - .env
  mopidy:
    container_name: mopidy
    build: 
      context: mopidy/

    ports:
      - "6600:6600"
      - "6680:6680"
 
  snapserver:
      image: jaedb/snapserver
      ports:
        - 1704:1704
        - 1705:1705
        - 1780:1780
      volumes:
        - /tmp/snapserver:/tmp
        - ./docker/snapserver.conf:/etc/snapserver.conf